name: Build

on:
  push:
    branches:
      - feat/project-update

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Ensure we can build the image
      run: docker build -t test:test --target server .