version: '3.3'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - /code/node_modules
      - .:/code
    ports:
      - 2000:2000
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2.00'
          memory: 1024M
    networks:
      - proxy

networks:
  proxy:
    external: true

