version: '3.5'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-static
    ports:
      - 8181:8181
    networks:
      - proxy
    command: |
      /bin/bash -c "echo '
      server {
        listen 8181;
        add_header X-Frame-Options "SAMEORIGIN";
        root /usr/share/nginx/html;
        index index.html;

        # define error page
        error_page 404 = @notfound;

        # error page location redirect 301
        location @notfound {
            return 301 /;
        }

        server_name clin.cr-ste-justine.xyz;
        #ssl_certificate /etc/letsencrypt/live/clin.cr-ste-justine.xyz/fullchain.pem;
        #ssl_certificate_key /etc/letsencrypt/live/clin.cr-ste-justine.xyz/privkey.pem;

        location /api/auth {  ### this service is defined in clin-proxy-api
            proxy_pass https://auth:3000/auth;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
        location /api/patient {  ### this service is defined in clin-proxy-api
            proxy_pass https://patient:4000/patient;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
        location /api/variant {  ### this service is defined in clin-proxy-api
            proxy_pass https://variant:5001/variant;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
        location /api/meta {  ### this service is defined in clin-proxy-api
            proxy_pass https://meta:7000/meta;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  proxy:
    name: proxy
