version: '3.3'
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-dev
      #dockerfile: Dockerfile
    image: localhost:5000/clin-frontend-dev
    volumes:
      - /code/node_modules
      - .:/code
    ports:
      - 2000:2000
    deploy:
      replicas: 2
    #command: ["pnpm", "run", "start"]
    networks:
      - proxy

networks:
  proxy:
    external: true

