version: '3.3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-static
    image: localhost:5000/clin-frontend-nginx
    ports:
      - '80:80'
    networks:
      - proxy
    command: |
      /bin/bash -c "echo '
      server {
        listen 80;
        add_header X-Frame-Options "SAMEORIGIN";
        root /usr/share/nginx/html;
        index index.html;
        server_name localhost;

        location /api/auth {  ### this service is defined in clin-proxy-api
            proxy_pass http://auth:3000/auth;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
        location /api/patient {  ### this service is defined in clin-proxy-api
            proxy_pass http://patient:4000/patient;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  webnet:
  proxy:
    external: true
