#!/bin/sh

cat > /usr/share/nginx/html/config.js <<- EndOfConf
window.env = {
    REACT_APP_PATIENT_SERVICE_URL: "$PATIENT_SERVICE_URL",
    REACT_APP_VARIANT_SERVICE_URL: "$VARIANT_SERVICE_URL",
    REACT_APP_GENE_SERVICE_URL: "$GENE_SERVICE_URL",
    REACT_APP_META_SERVICE_URL: "$META_SERVICE_URL",
    REACT_APP_FHIR_SERVICE_URL: "$FHIR_SERVICE_URL",
    REACT_APP_HPO_SERVICE_URL: "$HPO_SERVICE_URL",
    REACT_APP_KEYCLOAK_CONFIG: "$KEYCLOAK_CONFIG"
}
EndOfConf

exec "$@"