export const START_LOADING_ANIMATION = 'START_LOADING_ANIMATION';
export const STOP_LOADING_ANIMATION = 'STOP_LOADING_ANIMATION';

export const START_SUBLOADING_ANIMATION = 'START_SUBLOADING_ANIMATION';
export const STOP_SUBLOADING_ANIMATION = 'STOP_SUBLOADING_ANIMATION';

export const NOTIFICATION = 'NOTIFICATION';

export const APP_FETCH_REQUESTED = 'APP_FETCH_REQUESTED';
export const APP_FETCH_SUCCEEDED = 'APP_FETCH_SUCCEEDED';
export const APP_FETCH_FAILED = 'APP_FETCH_FAILED';

export const APP_CHANGE_LANGUAGE_REQUESTED = 'APP_CHANGE_LANGUAGE_REQUESTED';
export const APP_CHANGE_LANGUAGE_SUCCEEDED = 'APP_CHANGE_LANGUAGE_SUCCEEDED';
export const APP_CHANGE_LANGUAGE_FAILED = 'APP_CHANGE_LANGUAGE_FAILED';

export const ROUTER_NAVIGATION_REQUESTED = 'ROUTER_NAVIGATION_REQUESTED';
export const ROUTER_NAVIGATION_SUCCEEDED = 'ROUTER_NAVIGATION_SUCCEEDED';
export const ROUTER_NAVIGATION_FAILED = 'ROUTER_NAVIGATION_FAILED';

export const NAVIGATION_PATIENT_SCREEN_REQUESTED = 'NAVIGATION_PATIENT_SCREEN_REQUESTED';
export const NAVIGATION_PATIENT_SCREEN_SUCCEEDED = 'NAVIGATION_PATIENT_SCREEN_SUCCEEDED';
export const NAVIGATION_PATIENT_SCREEN_FAILED = 'NAVIGATION_PATIENT_SCREEN_FAILED';

export const NAVIGATION_PATIENT_VARIANT_SCREEN_REQUESTED = 'NAVIGATION_PATIENT_VARIANT_SCREEN_REQUESTED';
export const NAVIGATION_PATIENT_VARIANT_SCREEN_SUCCEEDED = 'NAVIGATION_PATIENT_VARIANT_SCREEN_SUCCEEDED';
export const NAVIGATION_PATIENT_VARIANT_SCREEN_FAILED = 'NAVIGATION_PATIENT_VARIANT_SCREEN_FAILED';

export const NAVIGATION_PATIENT_SEARCH_SCREEN_REQUESTED = 'NAVIGATION_PATIENT_SEARCH_SCREEN_REQUESTED';
export const NAVIGATION_PATIENT_SEARCH_SCREEN_SUCCEEDED = 'NAVIGATION_PATIENT_SEARCH_SCREEN_SUCCEEDED';
export const NAVIGATION_PATIENT_SEARCH_SCREEN_FAILED = 'NAVIGATION_PATIENT_SEARCH_SCREEN_FAILED';

export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT_REQUESTED = 'USER_LOGOUT_REQUESTED';
export const USER_LOGOUT_SUCCEEDED = 'USER_LOGOUT_SUCCEEDED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const USER_SESSION_HAS_EXPIRED = 'USER_SESSION_HAS_EXPIRED';

export const USER_RECOVERY_REQUESTED = 'USER_RECOVERY_REQUESTED';
export const USER_RECOVERY_SUCCEEDED = 'USER_RECOVERY_SUCCEEDED';
export const USER_RECOVERY_FAILED = 'USER_RECOVERY_FAILED';

export const USER_PROFILE_REQUESTED = 'USER_PROFILE_REQUESTED';
export const USER_PROFILE_SUCCEEDED = 'USER_PROFILE_SUCCEEDED';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const USER_PROFILE_UPDATE_REQUESTED = 'USER_PROFILE_UPDATE_REQUESTED';
export const USER_PROFILE_UPDATE_SUCCEEDED = 'USER_PROFILE_UPDATE_SUCCEEDED';
export const USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE_UPDATE_FAILED';

export const PATIENT_FETCH_REQUESTED = 'PATIENT_FETCH_REQUESTED';
export const PATIENT_FETCH_SUCCEEDED = 'PATIENT_FETCH_SUCCEEDED';
export const PATIENT_FETCH_FAILED = 'PATIENT_FETCH_FAILED';

export const PATIENT_AUTOCOMPLETE_REQUESTED = 'PATIENT_AUTOCOMPLETE_REQUESTED';
export const PATIENT_AUTOCOMPLETE_SUCCEEDED = 'PATIENT_AUTOCOMPLETE_SUCCEEDED';
export const PATIENT_AUTOCOMPLETE_FAILED = 'PATIENT_AUTOCOMPLETE_FAILED';

export const PATIENT_SEARCH_REQUESTED = 'PATIENT_SEARCH_REQUESTED';
export const PATIENT_SEARCH_SUCCEEDED = 'PATIENT_SEARCH_SUCCEEDED';
export const PATIENT_SEARCH_FAILED = 'PATIENT_SEARCH_FAILED';

export const VARIANT_SCHEMA_REQUESTED = 'VARIANT_SCHEMA_REQUESTED';
export const VARIANT_SCHEMA_SUCCEEDED = 'VARIANT_SCHEMA_SUCCEEDED';
export const VARIANT_SCHEMA_FAILED = 'VARIANT_SCHEMA_FAILED';

export const PATIENT_VARIANT_QUERY_SELECTION = 'PATIENT_VARIANT_QUERY_SELECTION';
export const PATIENT_VARIANT_QUERY_DUPLICATION = 'PATIENT_VARIANT_QUERY_DUPLICATION';
export const PATIENT_VARIANT_STATEMENT_SORT = 'PATIENT_VARIANT_STATEMENT_SORT';
export const PATIENT_VARIANT_QUERY_REPLACEMENT = 'PATIENT_VARIANT_QUERY_REPLACEMENT';
export const PATIENT_VARIANT_QUERIES_REPLACEMENT = 'PATIENT_VARIANT_QUERIES_REPLACEMENT';
export const PATIENT_VARIANT_QUERY_REMOVAL = 'PATIENT_VARIANT_QUERY_REMOVAL';

export const PATIENT_VARIANT_SEARCH_REQUESTED = 'PATIENT_VARIANT_SEARCH_REQUESTED';
export const PATIENT_VARIANT_SEARCH_SUCCEEDED = 'PATIENT_VARIANT_SEARCH_SUCCEEDED';
export const PATIENT_VARIANT_SEARCH_FAILED = 'PATIENT_VARIANT_SEARCH_FAILED';

export const PATIENT_VARIANT_FACET_REQUESTED = 'PATIENT_VARIANT_FACET_REQUESTED';
export const PATIENT_VARIANT_FACET_SUCCEEDED = 'PATIENT_VARIANT_FACET_SUCCEEDED';
export const PATIENT_VARIANT_FACET_FAILED = 'PATIENT_VARIANT_FACET_FAILED';

export const PATIENT_VARIANT_COUNT_REQUESTED = 'PATIENT_VARIANT_COUNT_REQUESTED';
export const PATIENT_VARIANT_COUNT_SUCCEEDED = 'PATIENT_VARIANT_COUNT_SUCCEEDED';
export const PATIENT_VARIANT_COUNT_FAILED = 'PATIENT_VARIANT_COUNT_FAILED';

export const PATIENT_VARIANT_COMMIT_HISTORY = 'PATIENT_VARIANT_COMMIT_HISTORY';
export const PATIENT_VARIANT_UNDO = 'PATIENT_VARIANT_UNDO';

export const PATIENT_VARIANT_GET_STATEMENTS_REQUESTED = 'PATIENT_VARIANT_GET_STATEMENTS_REQUESTED';
export const PATIENT_VARIANT_GET_STATEMENTS_SUCCEEDED = 'PATIENT_VARIANT_GET_STATEMENTS_SUCCEEDED';
export const PATIENT_VARIANT_GET_STATEMENTS_FAILED = 'PATIENT_VARIANT_GET_STATEMENTS_FAILED';

export const PATIENT_VARIANT_CREATE_DRAFT_STATEMENT = 'PATIENT_VARIANT_CREATE_DRAFT_STATEMENT';

export const PATIENT_VARIANT_CREATE_STATEMENT_REQUESTED = 'PATIENT_VARIANT_CREATE_STATEMENT_REQUESTED';
export const PATIENT_VARIANT_CREATE_STATEMENT_SUCCEEDED = 'PATIENT_VARIANT_CREATE_STATEMENT_SUCCEEDED';
export const PATIENT_VARIANT_CREATE_STATEMENT_FAILED = 'PATIENT_VARIANT_CREATE_STATEMENT_FAILED';

export const PATIENT_VARIANT_UPDATE_STATEMENT_REQUESTED = 'PATIENT_VARIANT_UPDATE_STATEMENT_REQUESTED';
export const PATIENT_VARIANT_UPDATE_STATEMENT_SUCCEEDED = 'PATIENT_VARIANT_UPDATE_STATEMENT_SUCCEEDED';
export const PATIENT_VARIANT_UPDATE_STATEMENT_FAILED = 'PATIENT_VARIANT_UPDATE_STATEMENT_FAILED';

export const PATIENT_VARIANT_DELETE_STATEMENT_REQUESTED = 'PATIENT_VARIANT_DELETE_STATEMENT_REQUESTED';
export const PATIENT_VARIANT_DELETE_STATEMENT_SUCCEEDED = 'PATIENT_VARIANT_DELETE_STATEMENT_SUCCEEDED';
export const PATIENT_VARIANT_DELETE_STATEMENT_FAILED = 'PATIENT_VARIANT_DELETE_STATEMENT_FAILED';

export const PATIENT_VARIANT_SELECT_STATEMENT_REQUESTED = 'PATIENT_VARIANT_SELECT_STATEMENT_REQUESTED';
export const PATIENT_VARIANT_SELECT_STATEMENT_SUCCEEDED = 'PATIENT_VARIANT_SELECT_STATEMENT_SUCCEEDED';
export const PATIENT_VARIANT_SELECT_STATEMENT_FAILED = 'PATIENT_VARIANT_SELECT_STATEMENT_FAILED';

export const PATIENT_VARIANT_DUPLICATE_STATEMENT_REQUESTED = 'PATIENT_VARIANT_DUPLICATE_STATEMENT_REQUESTED';
export const PATIENT_VARIANT_DUPLICATE_STATEMENT_SUCCEEDED = 'PATIENT_VARIANT_DUPLICATE_STATEMENT_SUCCEEDED';
export const PATIENT_VARIANT_DUPLICATE_STATEMENT_FAILED = 'PATIENT_VARIANT_DUPLICATE_STATEMENT_FAILED';
