export const APP_ERROR = 'APP_ERROR';

export const START_LOADING_ANIMATION = 'START_LOADING_ANIMATION';
export const STOP_LOADING_ANIMATION = 'STOP_LOADING_ANIMATION';

export const APP_FETCH_REQUESTED = 'APP_FETCH_REQUESTED';
export const APP_FETCH_SUCCEEDED = 'APP_FETCH_SUCCEEDED';
export const APP_FETCH_FAILED = 'APP_FETCH_FAILED';

export const USER_FETCH_REQUESTED = 'USER_FETCH_REQUESTED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
