---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clin-frontend
spec:
  template:
    spec:
      containers:
        - image: chusj/clin-frontend:aefc01277be3a1655fcf24d31afa4da95e923b1c
          name: clin-frontend