export const INVALID_TYPE_VALUE = [
  {
    id: '1',
    status: 'draft',
    organization: {
      id: 'Organization/CHUSJ',
      name: '',
    },
    lastName: 'Sanchez',
    firstName: 'Rick',
    gender: 'Male',
    birthDate: '2021-01-01',
    practitioner: {
      id: 'PractitionerRole/PROLE-s0me-id',
      lastName: 'Smith',
      firstName: 'Jerry',
    },
    test: 'WXS',
    prescription: '2021-01-01',
    mrn: '1324',
    ramq: '',
    position: 'Proband',
    familyId: '1',
    familyType: 'trio',
    ethnicity: '',
    bloodRelationship: '',
    request: '1',
    timestamp: '2021-01-01T12:19:21.297388Z',
    submitted: false,
  },
];

export const INVALID_TEST_VALUE = [
  {
    id: '1',
    status: 'draft',
    organization: {
      id: 'Organization/CHUSJ',
      name: '',
    },
    lastName: 'Sanchez',
    firstName: 'Rick',
    gender: 'Male',
    birthDate: '2021-01-01',
    practitioner: {
      id: 'PractitionerRole/PROLE-s0me-id',
      lastName: 'Smith',
      firstName: 'Jerry',
    },
    test: 'NOT_WXS',
    prescription: '2021-01-01',
    mrn: '1324',
    ramq: '',
    position: 'Proband',
    familyId: '1',
    familyType: 'trio',
    ethnicity: '',
    bloodRelationship: '',
    request: '1',
    timestamp: '2021-01-01T12:19:21.297388Z',
    submitted: false,
  },
];

export const VALID_VALUE_ONE_PATIENT = [
  {
    id: 'PA1',
    status: 'active',
    organization: {
      id: 'Organization/CHUSJ',
      name: '',
    },
    lastName: 'Sanchez',
    firstName: 'Rick',
    gender: 'Male',
    birthDate: '2021-01-01',
    practitioner: {
      id: 'PractitionerRole/PROLE-s0me-id',
      lastName: 'Smith',
      firstName: 'Jerry',
    },
    test: 'WXS',
    prescription: '2021-01-01',
    mrn: '1234',
    ramq: '',
    position: 'Proband',
    familyId: 'FA1',
    familyType: 'trio',
    ethnicity: '',
    bloodRelationship: '',
    request: 'SR1',
    timestamp: '2021-01-01T12:19:21.297388Z',
    submitted: false,
  },
];

export const VALID_VALUE_MULTIPLE_PATIENT = [
  {
    id: 'PA1',
    status: 'active',
    organization: {
      id: 'Organization/CHUSJ',
      name: '',
    },
    lastName: 'Sanchez',
    firstName: 'Rick',
    gender: 'Male',
    birthDate: '2021-01-01',
    practitioner: {
      id: 'PractitionerRole/PROLE-s0me-id',
      lastName: 'Smith',
      firstName: 'Jerry',
    },
    test: 'WXS',
    prescription: '2021-01-01',
    mrn: '1234',
    ramq: '',
    position: 'Proband',
    familyId: 'FA1',
    familyType: 'trio',
    ethnicity: '',
    bloodRelationship: '',
    request: 'SR1',
    timestamp: '2021-01-01T12:19:21.297388Z',
    submitted: false,
  },
  {
    id: 'PA2',
    status: 'active',
    organization: {
      id: 'Organization/CHUSJ',
      name: '',
    },
    lastName: 'Smith',
    firstName: 'Morty',
    gender: 'Male',
    birthDate: '2006-10-05',
    practitioner: {
      id: 'PractitionerRole/PROLE-s0me-id',
      lastName: 'Smith',
      firstName: 'Jerry',
    },
    test: 'WXS',
    prescription: '2021-01-01',
    mrn: '4321',
    ramq: '',
    position: 'Proband',
    familyId: 'FA1',
    familyType: 'trio',
    ethnicity: '',
    bloodRelationship: '',
    request: 'SR2',
    timestamp: '2021-01-01T12:19:21.297388Z',
    submitted: false,
  }];
